services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: operasional-btm-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - operasional
    deploy:
      resources:
        limits:
          memory: 250M

  webserver:
    image: nginx:alpine
    container_name: operasional-btm-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - operasional
    deploy:
      resources:
        limits:
          memory: 100M

  db:
    image: mysql:8.0
    container_name: operasional-btm-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_bengkel_btm
      MYSQL_ROOT_PASSWORD: pw123
      MYSQL_USER: laravel
      MYSQL_PASSWORD: pw123
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - operasional
    command: >
      --performance_schema=OFF
      --innodb_buffer_pool_size=64M
      --innodb_log_buffer_size=16M
      --max_connections=50
    deploy:
      resources:
        limits:
          memory: 300M

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: operasional-btm-phpmyadmin
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: operasional-btm-db
  #     PMA_PORT: 3306
  #   depends_on:
  #     - db
  #   networks:
  #     - operasional

networks:
  operasional:

volumes:
  dbdata:
